"""
Ledge → C Code Generator
=========================
Compiles Ledge programs to portable C99 that gcc can compile to native binaries.

This is the primary native compiler backend for Ledge v1.2.

Architecture:
  Ledge source
    → AST (parser.py)
    → C99 source (ccodegen.py)
    → Native binary (via gcc/clang)

Type mapping:
  number  → double
  text    → LedgeStr* (reference-counted string)
  truth   → int (0/1)
  nothing → special NOTHING sentinel
  list    → LedgeList* (dynamic array)
  map     → LedgeMap* (hash map)
  Uncertain[T] → LedgeUncertain* {value, confidence, source}
  function → function pointer + closure struct

Reference counting GC:
  Every heap-allocated value is reference counted.
  ldg_incref / ldg_decref manage lifetime.
  No cycles (by design — Ledge has no circular references in practice).

Performance target:
  Numeric compute: 10-50x faster than CPython
  String heavy: 3-5x faster
  Mixed AI workload: 2-5x faster
"""

from __future__ import annotations
from typing import List, Set
import re


# ── C Runtime Header ────────────────────────────────────────────────────────

RUNTIME_H = r"""
/* Ledge Runtime — generated by ledge_lang.compiler.ccodegen */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <assert.h>

/* ── Value types ──────────────────────────────────────────────────────────── */

typedef enum {
    LDG_NOTHING  = 0,
    LDG_NUMBER   = 1,
    LDG_TEXT     = 2,
    LDG_TRUTH    = 3,
    LDG_LIST     = 4,
    LDG_MAP      = 5,
    LDG_FN       = 6,
    LDG_UNCERTAIN = 7,
} LdgType;

typedef struct LdgVal LdgVal;
typedef struct LdgList LdgList;
typedef struct LdgMap LdgMap;
typedef struct LdgFn LdgFn;

struct LdgVal {
    LdgType type;
    int refcount;
    union {
        double   number;
        char*    text;
        int      truth;
        LdgList* list;
        LdgMap*  map;
        LdgFn*   fn;
        struct { LdgVal* value; double confidence; char* source; }* uncertain;
    } v;
};

/* ── Singletons ───────────────────────────────────────────────────────────── */
static LdgVal LDG_NOTHING_VAL = { .type = LDG_NOTHING, .refcount = 9999 };
static LdgVal LDG_TRUE_VAL    = { .type = LDG_TRUTH,   .refcount = 9999, .v.truth = 1 };
static LdgVal LDG_FALSE_VAL   = { .type = LDG_TRUTH,   .refcount = 9999, .v.truth = 0 };

#define LDG_NOTHING_PTR (&LDG_NOTHING_VAL)
#define LDG_TRUE_PTR    (&LDG_TRUE_VAL)
#define LDG_FALSE_PTR   (&LDG_FALSE_VAL)

/* ── Reference counting ───────────────────────────────────────────────────── */
static inline LdgVal* ldg_incref(LdgVal* v) {
    if (v && v->refcount < 9999) v->refcount++;
    return v;
}

static void ldg_free(LdgVal* v);

static inline void ldg_decref(LdgVal* v) {
    if (!v || v->refcount >= 9999) return;
    v->refcount--;
    if (v->refcount <= 0) ldg_free(v);
}

/* ── Value constructors ───────────────────────────────────────────────────── */
static LdgVal* ldg_number(double n) {
    LdgVal* v = malloc(sizeof(LdgVal));
    v->type = LDG_NUMBER; v->refcount = 1; v->v.number = n;
    return v;
}

static LdgVal* ldg_text(const char* s) {
    LdgVal* v = malloc(sizeof(LdgVal));
    v->type = LDG_TEXT; v->refcount = 1;
    v->v.text = strdup(s ? s : "");
    return v;
}

/* ── List implementation ──────────────────────────────────────────────────── */
struct LdgList {
    int refcount;
    int len;
    int cap;
    LdgVal** items;
};

static LdgList* ldg_list_new() {
    LdgList* l = malloc(sizeof(LdgList));
    l->refcount = 1; l->len = 0; l->cap = 4;
    l->items = malloc(4 * sizeof(LdgVal*));
    return l;
}

static LdgList* ldg_list_append(LdgList* lst, LdgVal* item) {
    /* Returns new list (copy-on-write semantics) */
    LdgList* nl = malloc(sizeof(LdgList));
    nl->refcount = 1;
    nl->len = lst->len + 1;
    nl->cap = nl->len + 4;
    nl->items = malloc(nl->cap * sizeof(LdgVal*));
    for (int i = 0; i < lst->len; i++) {
        nl->items[i] = ldg_incref(lst->items[i]);
    }
    nl->items[lst->len] = ldg_incref(item);
    return nl;
}

static LdgVal* ldg_list_val(LdgList* l) {
    LdgVal* v = malloc(sizeof(LdgVal));
    v->type = LDG_LIST; v->refcount = 1; v->v.list = l;
    return v;
}

/* ── Arithmetic operations ────────────────────────────────────────────────── */
static LdgVal* ldg_add(LdgVal* a, LdgVal* b) {
    if (a->type == LDG_NUMBER && b->type == LDG_NUMBER)
        return ldg_number(a->v.number + b->v.number);
    if (a->type == LDG_TEXT || b->type == LDG_TEXT) {
        /* String concatenation */
        char buf_a[64], buf_b[64];
        const char* sa = (a->type == LDG_TEXT) ? a->v.text :
                         (a->type == LDG_NUMBER) ? (snprintf(buf_a,64,
                             fmod(a->v.number,1.0)==0?"%.0f":"%g",
                             a->v.number),buf_a) : "nothing";
        const char* sb = (b->type == LDG_TEXT) ? b->v.text :
                         (b->type == LDG_NUMBER) ? (snprintf(buf_b,64,
                             fmod(b->v.number,1.0)==0?"%.0f":"%g",
                             b->v.number),buf_b) : "nothing";
        char* result = malloc(strlen(sa) + strlen(sb) + 1);
        strcpy(result, sa); strcat(result, sb);
        LdgVal* rv = ldg_text(result); free(result);
        return rv;
    }
    return LDG_NOTHING_PTR;
}

static LdgVal* ldg_sub(LdgVal* a, LdgVal* b) {
    if (a->type == LDG_NUMBER && b->type == LDG_NUMBER)
        return ldg_number(a->v.number - b->v.number);
    return LDG_NOTHING_PTR;
}

static LdgVal* ldg_mul(LdgVal* a, LdgVal* b) {
    if (a->type == LDG_NUMBER && b->type == LDG_NUMBER)
        return ldg_number(a->v.number * b->v.number);
    return LDG_NOTHING_PTR;
}

static LdgVal* ldg_div(LdgVal* a, LdgVal* b) {
    if (a->type == LDG_NUMBER && b->type == LDG_NUMBER) {
        if (b->v.number == 0.0) return LDG_NOTHING_PTR;
        return ldg_number(a->v.number / b->v.number);
    }
    return LDG_NOTHING_PTR;
}

static LdgVal* ldg_eq(LdgVal* a, LdgVal* b) {
    if (a->type == LDG_NOTHING && b->type == LDG_NOTHING) return LDG_TRUE_PTR;
    if (a->type == LDG_NOTHING || b->type == LDG_NOTHING) return LDG_FALSE_PTR;
    if (a->type == LDG_NUMBER && b->type == LDG_NUMBER)
        return a->v.number == b->v.number ? LDG_TRUE_PTR : LDG_FALSE_PTR;
    if (a->type == LDG_TEXT && b->type == LDG_TEXT)
        return strcmp(a->v.text, b->v.text) == 0 ? LDG_TRUE_PTR : LDG_FALSE_PTR;
    if (a->type == LDG_TRUTH && b->type == LDG_TRUTH)
        return a->v.truth == b->v.truth ? LDG_TRUE_PTR : LDG_FALSE_PTR;
    /* true != 1, false != 0, nothing != false — Ledge semantics */
    if (a->type != b->type) return LDG_FALSE_PTR;
    return LDG_FALSE_PTR;
}

static int ldg_truthy(LdgVal* v) {
    if (!v || v->type == LDG_NOTHING) return 0;
    if (v->type == LDG_TRUTH) return v->v.truth;
    if (v->type == LDG_NUMBER) return v->v.number != 0.0;
    if (v->type == LDG_TEXT) return strlen(v->v.text) > 0;
    if (v->type == LDG_LIST) return v->v.list && v->v.list->len > 0;
    return 1;
}

/* ── Output ───────────────────────────────────────────────────────────────── */
static void ldg_show(LdgVal* v) {
    if (!v || v->type == LDG_NOTHING) { printf("nothing\n"); return; }
    switch (v->type) {
        case LDG_NUMBER: {
            double n = v->v.number;
            if (n == (long long)n) printf("%.0f\n", n);
            else printf("%g\n", n);
            break;
        }
        case LDG_TEXT:  printf("%s\n", v->v.text); break;
        case LDG_TRUTH: printf("%s\n", v->v.truth ? "true" : "false"); break;
        case LDG_LIST: {
            printf("[");
            for (int i = 0; i < v->v.list->len; i++) {
                if (i > 0) printf(", ");
                LdgVal* item = v->v.list->items[i];
                if (item->type == LDG_NUMBER) {
                    double n = item->v.number;
                    if (n == (long long)n) printf("%.0f", n);
                    else printf("%g", n);
                } else if (item->type == LDG_TEXT) printf("%s", item->v.text);
                else if (item->type == LDG_TRUTH) printf("%s", item->v.truth?"true":"false");
                else printf("nothing");
            }
            printf("]\n");
            break;
        }
        default: printf("nothing\n");
    }
}

/* ── Builtins ─────────────────────────────────────────────────────────────── */
static LdgVal* ldg_sqrt(LdgVal* v) {
    if (v->type != LDG_NUMBER || v->v.number < 0) return LDG_NOTHING_PTR;
    return ldg_number(sqrt(v->v.number));
}
static LdgVal* ldg_abs_val(LdgVal* v) {
    if (v->type != LDG_NUMBER) return LDG_NOTHING_PTR;
    return ldg_number(fabs(v->v.number));
}
static LdgVal* ldg_len(LdgVal* v) {
    if (v->type == LDG_TEXT) return ldg_number(strlen(v->v.text));
    if (v->type == LDG_LIST) return ldg_number(v->v.list->len);
    return LDG_NOTHING_PTR;
}
static LdgVal* ldg_sum_list(LdgVal* v) {
    if (v->type != LDG_LIST) return ldg_number(0);
    double s = 0;
    for (int i = 0; i < v->v.list->len; i++) {
        LdgVal* item = v->v.list->items[i];
        if (item->type == LDG_NUMBER) s += item->v.number;
    }
    return ldg_number(s);
}

static void ldg_free(LdgVal* v) {
    if (!v || v->refcount >= 9999) return;
    if (v->type == LDG_TEXT && v->v.text) free(v->v.text);
    if (v->type == LDG_LIST && v->v.list) {
        for (int i = 0; i < v->v.list->len; i++) ldg_decref(v->v.list->items[i]);
        free(v->v.list->items);
        free(v->v.list);
    }
    free(v);
}
"""


# ── C Code Generator ─────────────────────────────────────────────────────────



def is_numeric_function(fn_node) -> bool:
    """
    Conservative check: function is purely numeric if it ONLY uses:
      - Number literals and arithmetic (+, -, *, /)
      - Variables that hold numbers
      - Recursive calls to the same function
      - If/while/repeat with numeric conditions
      - Return statements with numeric expressions
    
    Explicitly NOT numeric:
      - Comparisons (= != < > <= >=) — would print 1.0/0.0 not true/false
      - Boolean literals (true/false)
      - NothingLit or divide() — nothing can't be represented as double
      - Strings
      - AI instructions
      - FFI imports
    """
    fn_name = getattr(fn_node, 'name', None)
    
    def check_expr(node):
        if node is None: return True
        t = type(node).__name__
        if t == "NumberLit": return True
        if t in ("StringLit", "BoolLit", "NothingLit"): return False  # not numeric
        if t == "Identifier": return True  # assume numeric variable
        if t == "BinOp":
            op = getattr(node, 'op', '')
            # Only arithmetic — NOT comparison operators
            if op in ('+', '-', '*', '/'):
                return check_expr(node.left) and check_expr(node.right)
            return False  # comparison would produce true/false not number
        if t == "UnaryOp":
            op = getattr(node, 'op', '')
            if op == '-': return check_expr(node.operand)
            return False  # 'not' produces boolean
        if t == "LogicalOp":
            return False  # and/or produce booleans or fallback values
        if t == "Call":
            callee_name = getattr(node.callee, 'name', None) if hasattr(node, 'callee') else None
            # Safe builtins for numeric mode
            if callee_name in ('sqrt', 'abs', 'floor', 'ceil', 'round', 'power'):
                return True
            # divide() returns nothing — not numeric
            if callee_name == 'divide':
                return False
            # Recursive calls to same function are OK
            if callee_name == fn_name:
                return True
            # Other function calls — conservatively assume numeric
            if callee_name:
                return True
            return False
        if t == "Fallback":
            return False  # or operator might return nothing
        if t in ("AnalyzeExpr", "ClassifyExpr", "GenerateExpr", "AskExpr"):
            return False
        return False  # unknown — be conservative

    def check_stmts(stmts):
        for stmt in stmts:
            t = type(stmt).__name__
            if t == "Show":
                expr = getattr(stmt, 'expr', None)
                if not check_expr(expr): return False
            elif t in ("Define", "Assign"):
                val = getattr(stmt, 'value', None)
                if not check_expr(val): return False
            elif t == "Return":
                val = getattr(stmt, 'value', None)
                if val and not check_expr(val): return False
            elif t in ("If", "While", "Repeat"):
                cond = getattr(stmt, 'condition', None) or getattr(stmt, 'count', None)
                if cond and not check_expr(cond): return False
                body = getattr(stmt, 'body', None)
                if body:
                    body_stmts = body.stmts if hasattr(body, 'stmts') else []
                    if not check_stmts(body_stmts): return False
                # Check all branches of if
                branches = getattr(stmt, 'branches', [])
                for _, blk in branches:
                    if blk and not check_stmts(blk.stmts if hasattr(blk, 'stmts') else []):
                        return False
                else_blk = getattr(stmt, 'else_block', None)
                if else_blk and not check_stmts(else_blk.stmts if hasattr(else_blk, 'stmts') else []):
                    return False
            elif t in ("AnalyzeExpr", "ClassifyExpr", "GenerateExpr"):
                return False
            elif t not in ("Return",):
                # Conservative: unknown statement type = not numeric
                pass
        return True

    if not hasattr(fn_node, 'body'): return False
    body = fn_node.body
    stmts = body.stmts if hasattr(body, 'stmts') else []
    return check_stmts(stmts)

class CCodegen:
    """Generates C99 code from a Ledge AST."""

    def __init__(self):
        self._functions: List[str] = []
        self._main_stmts: List[str] = []
        self._var_counter = 0
        self._label_counter = 0
        self._scope_stack: List[Set[str]] = [set()]
        self._fn_defs: List[str] = []

    def fresh_var(self, prefix="t") -> str:
        self._var_counter += 1
        return f"_{prefix}{self._var_counter}"

    def fresh_label(self, prefix="L") -> str:
        self._label_counter += 1
        return f"{prefix}{self._label_counter}"

    def emit_fn(self, code: str):
        self._fn_defs.append(code)

    def compile(self, program) -> str:
        """Compile AST to complete C source.
        
        Uses numeric mode (unboxed doubles) for the main body when the program
        is purely numeric — eliminates malloc/free overhead per operation.
        """
        # First pass: collect function definitions
        for stmt in program.stmts:
            if type(stmt).__name__ == "Define" and stmt.value and \
               type(stmt.value).__name__ == "FuncDef":
                self._compile_funcdef(stmt.name, stmt.value)

        # Detect if main body is purely numeric (no strings, lists, AI, FFI)
        main_stmts = [s for s in program.stmts
                      if not (type(s).__name__ == "Define" and s.value and
                              type(s.value).__name__ == "FuncDef")]
        
        from dataclasses import dataclass
        @dataclass
        class _FakeNode:
            stmts: list
            params: list = None
            body: '_FakeNode' = None
        fake_fn = _FakeNode(stmts=main_stmts)
        fake_fn.body = fake_fn
        numeric_main = is_numeric_function(fake_fn)

        # Second pass: compile main body
        body_lines = []
        if numeric_main:
            # NUMERIC MODE: zero-overhead main (no boxing for constants/variables)
            for stmt in main_stmts:
                body_lines.extend(self._compile_stmt_num(stmt, "    "))
        else:
            for stmt in main_stmts:
                body_lines.extend(self._compile_stmt(stmt, "    "))

        fn_section = "\n".join(self._fn_defs)
        main_body = "\n".join(body_lines)

        return RUNTIME_H + "\n" + fn_section + "\n\nint main(void) {\n" + main_body + "\n    return 0;\n}\n"

    def _compile_funcdef(self, name: str, fn_node) -> None:
        """Emit a C function definition, in numeric mode if possible."""
        params = fn_node.params
        is_numeric = is_numeric_function(fn_node)
        self._numeric_fns = getattr(self, "_numeric_fns", set())
        
        if is_numeric and params:
            # NUMERIC MODE: use raw doubles — no malloc, no GC overhead
            self._numeric_fns.add(name)
            param_decls = ", ".join(f"double {p[0]}" for p in params)
            lines = [f"static double fn_num_{name}({param_decls}) {{"]
            # Create var_ aliases for parameters
            for p in params:
                lines.append(f"    double var_{p[0]} = {p[0]};")
            # In numeric mode, variables are plain doubles
            for stmt in fn_node.body.stmts:
                lines.extend(self._compile_stmt_num(stmt, "    "))
            lines.append("    return 0.0;")
            lines.append("}")
            self.emit_fn("\n".join(lines))
            
            # Also emit a boxed wrapper for compatibility
            param_decls_box = ", ".join(f"LdgVal* {p[0]}" for p in params)
            wrap_args = ", ".join(f"{p[0]}->v.number" for p in params)
            wrapper = (
                f"static LdgVal* fn_{name}({param_decls_box}) {{\n"
                f"    return ldg_number(fn_num_{name}({wrap_args}));\n"
                f"}}"
            )
            self.emit_fn(wrapper)
        else:
            # BOXED MODE: use LdgVal* for mixed-type functions
            param_decls = ", ".join(f"LdgVal* {p[0]}" for p in params)
            if not param_decls:
                param_decls = "void"
            lines = [f"static LdgVal* fn_{name}({param_decls}) {{"]
            for p in params:
                lines.append(f"    LdgVal* var_{p[0]} = {p[0]};")
            for stmt in fn_node.body.stmts:
                lines.extend(self._compile_stmt(stmt, "    "))
            lines.append("    return LDG_NOTHING_PTR;")
            lines.append("}")
            self.emit_fn("\n".join(lines))

    def _compile_stmt_num(self, node, indent="    ") -> list:
        """Compile statement in numeric mode (raw doubles, no boxing)."""
        t = type(node).__name__
        lines = []
        if t == "Define":
            val, vl = self._compile_expr_num(node.value, indent)
            lines.extend(vl)
            lines.append(f"{indent}double var_{node.name} = {val};")
        elif t == "Assign":
            val, vl = self._compile_expr_num(node.value, indent)
            lines.extend(vl)
            lines.append(f"{indent}var_{node.name} = {val};")
        elif t == "Return":
            if node.value:
                val, vl = self._compile_expr_num(node.value, indent)
                lines.extend(vl)
                lines.append(f"{indent}return {val};")
            else:
                lines.append(f"{indent}return 0.0;")
        elif t == "If":
            for i, (cond, blk) in enumerate(node.branches):
                cv, cl = self._compile_expr_num(cond, indent)
                lines.extend(cl)
                kw = "if" if i == 0 else "else if"
                lines.append(f"{indent}{kw} ({cv}) {{")
                for s in blk.stmts:
                    lines.extend(self._compile_stmt_num(s, indent + "    "))
                lines.append(f"{indent}}}")
            if node.else_block:
                lines.append(f"{indent}else {{")
                for s in node.else_block.stmts:
                    lines.extend(self._compile_stmt_num(s, indent + "    "))
                lines.append(f"{indent}}}")
        elif t == "While":
            loop_l = self.fresh_label("wn")
            exit_l = self.fresh_label("wne")
            lines.append(f"{indent}{loop_l}:;")
            cv, cl = self._compile_expr_num(node.condition, indent)
            lines.extend(cl)
            lines.append(f"{indent}if (!({cv})) goto {exit_l};")
            for s in node.body.stmts:
                lines.extend(self._compile_stmt_num(s, indent + "    "))
            lines.append(f"{indent}goto {loop_l};")
            lines.append(f"{indent}{exit_l}:;")
        elif t == "Repeat":
            if node.count is not None:
                ctr = self.fresh_var("i")
                lim, ll = self._compile_expr_num(node.count, indent)
                lines.extend(ll)
                lines.append(f"{indent}for (int {ctr} = 0; {ctr} < (int)({lim}); {ctr}++) {{")
                for s in node.body.stmts:
                    lines.extend(self._compile_stmt_num(s, indent + "    "))
                lines.append(f"{indent}}}")
        elif t == "Show":
            val, vl = self._compile_expr_num(node.expr, indent)
            lines.extend(vl)
            # Print the double value like Ledge does
            pfmt = '{ double _sv = ' + val + '; if (_sv==(long long)_sv) printf("%.0f\\n",_sv); else printf("%g\\n",_sv); }'
            lines.append(indent + pfmt)
        else:
            lines.append(f"{indent}/* [{t}] */")
        return lines

    def _compile_expr_num(self, node, indent="    "):
        """Compile expression to raw double."""
        t = type(node).__name__
        lines = []
        if t == "NumberLit":
            return str(float(node.value)), lines
        if t == "BoolLit":
            return ("1.0" if node.value else "0.0"), lines
        if t == "NothingLit":
            return "0.0", lines
        if t == "Identifier":
            return f"var_{node.name}", lines
        if t == "BinOp":
            lv, ll = self._compile_expr_num(node.left, indent)
            rv, rl = self._compile_expr_num(node.right, indent)
            lines.extend(ll); lines.extend(rl)
            ops = {"+": "+", "-": "-", "*": "*", "/": "/",
                   "=": "==", "!=": "!=", "<": "<", ">": ">", "<=": "<=", ">=": ">="}
            if node.op in ops:
                if node.op == "/":
                    tmp = self.fresh_var("d")
                    lines.append(f"{indent}double {tmp} = ({rv} == 0.0) ? 0.0 : ({lv} / {rv});")
                    return tmp, lines
                return f"({lv} {ops[node.op]} {rv})", lines
            return "0.0", lines
        if t == "UnaryOp":
            ov, ol = self._compile_expr_num(node.operand, indent)
            lines.extend(ol)
            if node.op == "-": return f"(-{ov})", lines
            if node.op == "not": return f"(!{ov})", lines
            return ov, lines
        if t == "LogicalOp":
            lv, ll = self._compile_expr_num(node.left, indent)
            rv, rl = self._compile_expr_num(node.right, indent)
            lines.extend(ll); lines.extend(rl)
            if node.op == "and": return f"(({lv}) && ({rv}))", lines
            if node.op == "or":  return f"(({lv}) != 0.0 ? ({lv}) : ({rv}))", lines  # fallback semantics
            return "0.0", lines
        if t == "Fallback":
            ev, el = self._compile_expr_num(node.expr, indent)
            dv, dl = self._compile_expr_num(node.default, indent)
            lines.extend(el); lines.extend(dl)
            return f"(({ev}) ? ({ev}) : ({dv}))", lines
        if t == "Call":
            fn_name = getattr(node.callee, "name", None)
            nm_fns = getattr(self, "_numeric_fns", set())
            args_v = []
            for arg in node.args:
                av, al = self._compile_expr_num(arg, indent)
                lines.extend(al)
                args_v.append(av)
            args_s = ", ".join(args_v)
            if fn_name in nm_fns:
                return f"fn_num_{fn_name}({args_s})", lines
            if fn_name == "sqrt": return f"sqrt({args_v[0]})" if args_v else "0.0", lines
            if fn_name == "abs":  return f"fabs({args_v[0]})" if args_v else "0.0", lines
            if fn_name == "divide":
                if len(args_v) >= 2:
                    tmp = self.fresh_var("dv")
                    lines.append(f"{indent}double {tmp} = ({args_v[1]} == 0.0) ? 0.0 : ({args_v[0]} / {args_v[1]});")
                    return tmp, lines
                return "0.0", lines
            # Check if it's a known user function (including zero-arg)
            nm_fns = getattr(self, "_numeric_fns", set())
            if fn_name and fn_name in nm_fns:
                return f"fn_num_{fn_name}({args_s})", lines
            # Unknown — call boxed and unbox result
            tmp = self.fresh_var("bc")
            # For known user functions in boxed mode
            if fn_name:
                box_call = self.fresh_var("bv")
                lines.append(f"{indent}LdgVal* {box_call} = fn_{fn_name}({args_s});")
                lines.append(f"{indent}double {tmp} = ({box_call}->type == LDG_NUMBER) ? {box_call}->v.number : 0.0;")
                return tmp, lines
            return "0.0", lines
        return "0.0", lines

    def _compile_stmt(self, node, indent="    ") -> List[str]:
        t = type(node).__name__
        lines = []

        if t == "Define":
            if node.value and type(node.value).__name__ == "FuncDef":
                return []  # Already compiled
            val_var, val_lines = self._compile_expr(node.value, indent) if node.value else ("LDG_NOTHING_PTR", [])
            lines.extend(val_lines)
            lines.append(f"{indent}LdgVal* var_{node.name} = ldg_incref({val_var});")
            self._scope_stack[-1].add(node.name)

        elif t == "Assign":
            val_var, val_lines = self._compile_expr(node.value, indent)
            lines.extend(val_lines)
            lines.append(f"{indent}ldg_decref(var_{node.name});")
            lines.append(f"{indent}var_{node.name} = ldg_incref({val_var});")

        elif t == "Show":
            val_var, val_lines = self._compile_expr(node.expr, indent)
            lines.extend(val_lines)
            lines.append(f"{indent}ldg_show({val_var});")

        elif t == "If":
            for i, (cond, blk) in enumerate(node.branches):
                cond_var, cond_lines = self._compile_expr(cond, indent)
                lines.extend(cond_lines)
                kw = "if" if i == 0 else "else if"
                lines.append(f"{indent}{kw} (ldg_truthy({cond_var})) {{")
                for s in blk.stmts:
                    lines.extend(self._compile_stmt(s, indent + "    "))
                lines.append(f"{indent}}}")
            if node.else_block:
                lines.append(f"{indent}else {{")
                for s in node.else_block.stmts:
                    lines.extend(self._compile_stmt(s, indent + "    "))
                lines.append(f"{indent}}}")

        elif t == "While":
            cond_var = self.fresh_var("cond")
            loop_label = self.fresh_label("while")
            exit_label = self.fresh_label("while_end")
            lines.append(f"{indent}/* while loop */")
            lines.append(f"{indent}{loop_label}:;")
            cond_val, cond_lines = self._compile_expr(node.condition, indent)
            lines.extend(cond_lines)
            lines.append(f"{indent}if (!ldg_truthy({cond_val})) goto {exit_label};")
            for s in node.body.stmts:
                lines.extend(self._compile_stmt(s, indent + "    "))
            lines.append(f"{indent}goto {loop_label};")
            lines.append(f"{indent}{exit_label}:;")

        elif t == "Repeat":
            if node.count is not None:
                counter = self.fresh_var("i")
                limit_var, limit_lines = self._compile_expr(node.count, indent)
                lines.extend(limit_lines)
                lines.append(f"{indent}for (int {counter} = 0; {counter} < (int)({limit_var}->v.number); {counter}++) {{")
                for s in node.body.stmts:
                    lines.extend(self._compile_stmt(s, indent + "    "))
                lines.append(f"{indent}}}")

        elif t == "Return":
            if node.value:
                val_var, val_lines = self._compile_expr(node.value, indent)
                lines.extend(val_lines)
                lines.append(f"{indent}return {val_var};")
            else:
                lines.append(f"{indent}return LDG_NOTHING_PTR;")

        elif t == "For":
            iter_var = self.fresh_var("iter")
            idx_var = self.fresh_var("idx")
            it_val, it_lines = self._compile_expr(node.iterable, indent)
            lines.extend(it_lines)
            lines.append(f"{indent}LdgVal* {iter_var} = {it_val};")
            lines.append(f"{indent}if ({iter_var}->type == LDG_LIST) {{")
            lines.append(f"{indent}    for (int {idx_var} = 0; {idx_var} < {iter_var}->v.list->len; {idx_var}++) {{")
            lines.append(f"{indent}        LdgVal* var_{node.var} = ldg_incref({iter_var}->v.list->items[{idx_var}]);")
            for s in node.body.stmts:
                lines.extend(self._compile_stmt(s, indent + "        "))
            lines.append(f"{indent}    }}")
            lines.append(f"{indent}}}")

        elif t == "Check":
            # check/recover — simplified: just run body
            for s in node.body.stmts:
                lines.extend(self._compile_stmt(s, indent))
            if node.always_block:
                for s in node.always_block.stmts:
                    lines.extend(self._compile_stmt(s, indent))

        elif t == "ExprStmt":
            val_var, val_lines = self._compile_expr(node.expr, indent)
            lines.extend(val_lines)
            # Discard result

        else:
            lines.append(f"{indent}/* [unsupported: {t}] */")

        return lines

    def _compile_expr(self, node, indent="    "):
        """Returns (result_var_or_literal, list_of_setup_lines)."""
        t = type(node).__name__
        lines = []

        if t == "NumberLit":
            v = self.fresh_var("n")
            lines.append(f"{indent}LdgVal* {v} = ldg_number({float(node.value)});")
            return v, lines

        if t == "StringLit":
            escaped = node.value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')
            v = self.fresh_var("s")
            lines.append(f'{indent}LdgVal* {v} = ldg_text("{escaped}");')
            return v, lines

        if t == "BoolLit":
            return "LDG_TRUE_PTR" if node.value else "LDG_FALSE_PTR", lines

        if t == "NothingLit":
            return "LDG_NOTHING_PTR", lines

        if t == "Identifier":
            return f"var_{node.name}", lines

        if t == "BinOp":
            lv, ll = self._compile_expr(node.left, indent)
            rv, rl = self._compile_expr(node.right, indent)
            lines.extend(ll); lines.extend(rl)
            result = self.fresh_var("r")
            op_map = {
                "+": "ldg_add", "-": "ldg_sub", "*": "ldg_mul", "/": "ldg_div",
            }
            cmp_map = {
                "=": "ldg_eq",
                "!=": None, "<": None, ">": None, "<=": None, ">=": None,
            }
            if node.op in op_map:
                lines.append(f"{indent}LdgVal* {result} = {op_map[node.op]}({lv}, {rv});")
            elif node.op == "=":
                lines.append(f"{indent}LdgVal* {result} = ldg_eq({lv}, {rv});")
            elif node.op == "!=":
                eq_v = self.fresh_var("eq")
                lines.append(f"{indent}LdgVal* {eq_v} = ldg_eq({lv}, {rv});")
                lines.append(f"{indent}LdgVal* {result} = {eq_v}->v.truth ? LDG_FALSE_PTR : LDG_TRUE_PTR;")
            elif node.op in ("<", ">", "<=", ">="):
                cmp_ops = {"<": "<", ">": ">", "<=": "<=", ">=": ">="}
                op = cmp_ops[node.op]
                lines.append(f"{indent}LdgVal* {result} = ({lv}->type==LDG_NUMBER && {rv}->type==LDG_NUMBER && {lv}->v.number {op} {rv}->v.number) ? LDG_TRUE_PTR : LDG_FALSE_PTR;")
            else:
                lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR; /* unknown op: {node.op} */")
            return result, lines

        if t == "UnaryOp":
            ov, ol = self._compile_expr(node.operand, indent)
            lines.extend(ol)
            result = self.fresh_var("u")
            if node.op == "-":
                lines.append(f"{indent}LdgVal* {result} = ({ov}->type==LDG_NUMBER) ? ldg_number(-{ov}->v.number) : LDG_NOTHING_PTR;")
            elif node.op == "not":
                lines.append(f"{indent}LdgVal* {result} = ldg_truthy({ov}) ? LDG_FALSE_PTR : LDG_TRUE_PTR;")
            else:
                lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR;")
            return result, lines

        if t == "LogicalOp":
            lv, ll = self._compile_expr(node.left, indent)
            lines.extend(ll)
            result = self.fresh_var("logic")
            if node.op == "and":
                rv, rl = self._compile_expr(node.right, indent)
                lines.extend(rl)
                lines.append(f"{indent}LdgVal* {result} = (ldg_truthy({lv}) && ldg_truthy({rv})) ? LDG_TRUE_PTR : LDG_FALSE_PTR;")
            elif node.op == "or":
                # Ledge `a or b` = fallback: return a if truthy, else b
                rv, rl = self._compile_expr(node.right, indent)
                lines.extend(rl)
                lines.append(f"{indent}LdgVal* {result} = ldg_truthy({lv}) ? {lv} : {rv};")
            else:
                lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR;")
            return result, lines

        if t == "Fallback":
            ev, el = self._compile_expr(node.expr, indent)
            dv, dl = self._compile_expr(node.default, indent)
            lines.extend(el); lines.extend(dl)
            result = self.fresh_var("fallback")
            lines.append(f"{indent}LdgVal* {result} = ldg_truthy({ev}) ? {ev} : {dv};")
            return result, lines

        if t == "Call":
            fn_name = getattr(node.callee, 'name', None)
            args_compiled = []
            for arg in node.args:
                av, al = self._compile_expr(arg, indent)
                lines.extend(al)
                args_compiled.append(av)

            result = self.fresh_var("call")
            builtin_map = {
                "sqrt": lambda args: f"ldg_sqrt({args[0]})" if args else "LDG_NOTHING_PTR",
                "abs": lambda args: f"ldg_abs_val({args[0]})" if args else "LDG_NOTHING_PTR",
                "len": lambda args: f"ldg_len({args[0]})" if args else "LDG_NOTHING_PTR",
                "sum": lambda args: f"ldg_sum_list({args[0]})" if args else "ldg_number(0)",
                "divide": lambda args: f"ldg_div({args[0]}, {args[1]})" if len(args) >= 2 else "LDG_NOTHING_PTR",
            }

            if fn_name in builtin_map:
                expr = builtin_map[fn_name](args_compiled)
                lines.append(f"{indent}LdgVal* {result} = {expr};")
            elif fn_name:
                args_str = ", ".join(args_compiled)
                lines.append(f"{indent}LdgVal* {result} = fn_{fn_name}({args_str});")
            else:
                lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR; /* unknown fn */")
            return result, lines

        if t == "ListLit":
            list_var = self.fresh_var("list")
            items_compiled = []
            for item in node.items:
                iv, il = self._compile_expr(item, indent)
                lines.extend(il)
                items_compiled.append(iv)
            lines.append(f"{indent}LdgList* lst_{list_var} = ldg_list_new();")
            for iv in items_compiled:
                # Build the list inline
                lines.append(f"{indent}{{  LdgList* tmp = ldg_list_append(lst_{list_var}, {iv}); lst_{list_var} = tmp; }}")
            lines.append(f"{indent}LdgVal* {list_var} = ldg_list_val(lst_{list_var});")
            return list_var, lines

        if t == "Index":
            ov, ol = self._compile_expr(node.obj, indent)
            kv, kl = self._compile_expr(node.key, indent)
            lines.extend(ol); lines.extend(kl)
            result = self.fresh_var("idx")
            lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR;")
            lines.append(f"{indent}if ({ov}->type == LDG_LIST && {kv}->type == LDG_NUMBER) {{")
            lines.append(f"{indent}    int _i = (int){kv}->v.number;")
            lines.append(f"{indent}    if (_i >= 0 && _i < {ov}->v.list->len) {result} = {ov}->v.list->items[_i];")
            lines.append(f"{indent}}}")
            return result, lines

        # AI instructions — compile as stub returning uncertain with confidence=0
        if t in ("AnalyzeExpr", "ClassifyExpr", "GenerateExpr", "AskExpr", "EmbedExpr"):
            result = self.fresh_var("ai")
            lines.append(f"{indent}/* AI instruction {t} -- returns nothing without backend */")
            lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR;")
            return result, lines

        # Default: unsupported
        result = self.fresh_var("unsup")
        lines.append(f"{indent}LdgVal* {result} = LDG_NOTHING_PTR; /* {t} */")
        return result, lines


# ── Compilation pipeline ────────────────────────────────────────────────────

def compile_to_c(source: str) -> str:
    """Compile Ledge source to C99 source code."""
    from ..lexer import Lexer
    from ..parser import Parser
    tokens = Lexer(source).tokenize()
    program = Parser(tokens).parse()
    gen = CCodegen()
    return gen.compile(program)


def compile_to_native(source: str, output_path: str = "a.out",
                      optimize: bool = True) -> str:
    """
    Compile Ledge source to a native binary using gcc.

    Requirements: gcc (standard on Linux/macOS)

    Returns: path to the compiled binary
    """
    import subprocess, tempfile, os, shutil

    gcc = shutil.which('gcc') or shutil.which('cc')
    if not gcc:
        raise RuntimeError(
            "Native compilation requires gcc. Install it:\n"
            "  Ubuntu/Debian: sudo apt install gcc\n"
            "  macOS:         xcode-select --install"
        )

    c_source = compile_to_c(source)

    with tempfile.NamedTemporaryFile(suffix='.c', mode='w', delete=False) as f:
        f.write(c_source)
        c_path = f.name

    try:
        opt_flags = ['-O3', '-march=native'] if optimize else ['-O0']
        cmd = [gcc] + opt_flags + ['-o', output_path, c_path, '-lm']
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"GCC compilation failed:\n{result.stderr}")
        os.chmod(output_path, 0o755)
        return os.path.abspath(output_path)
    finally:
        os.unlink(c_path)
