"""
Ledge Natural Language Interface
=================================
Converts English descriptions to valid Ledge programs using heuristic patterns.
No API key required.
"""

from __future__ import annotations
import re
from typing import Dict, List, Optional, Tuple


class NaturalLanguageInterface:
    """
    Converts English descriptions to Ledge programs using pattern matching.
    No AI backend required — runs entirely from heuristics.
    """

    PATTERNS: Dict[str, List[str]] = {
        "classify":  ["classify", "categorize", "label",
                      "determine if", "is this", "what type"],
        "analyze":   ["analyze", "analyse", "examine",
                      "evaluate", "assess"],
        "triage":    ["triage", "urgent", "urgency", "priority",
                      "should i escalate", "is this critical"],
        "sentiment": ["sentiment", "positive or negative",
                      "feel about", "opinion", "how does"],
        "summarize": ["summarize", "summary", "brief",
                      "key points", "main ideas"],
    }

    DOMAIN_PATTERNS: Dict[str, List[str]] = {
        "medical":   ["patient", "symptom", "symptoms", "diagnosis",
                      "medical", "health", "clinical", "doctor",
                      "triage", "emergency"],
        "legal":     ["contract", "legal", "clause", "liability",
                      "compliance", "law", "attorney"],
        "financial": ["financial", "finance", "investment", "risk",
                      "portfolio", "stock", "loan", "fraud"],
        "email":     ["email", "spam", "inbox", "message"],
        "social":    ["review", "sentiment", "opinion",
                      "feedback", "comment"],
    }

    # More-specific intents checked before generic ones
    _INTENT_ORDER = ["triage", "sentiment", "summarize", "classify", "analyze"]

    # ── Public API ────────────────────────────────────────────────────────────

    def parse_intent(self, text: str) -> Dict:
        """
        Detect intent, domain, labels, and subject from English text.

        Returns:
        {
          "intent":    "classify" | "analyze" | "triage" | "sentiment" | "summarize",
          "subject":   "extracted subject phrase",
          "labels":    ["label1", "label2"] | None,
          "threshold": 0.85,
          "domain":    "medical" | "legal" | "email" | "social" | "general" | ...
        }
        """
        lower = text.lower()

        # Intent: walk priority list, take first match
        intent = "classify"  # default
        for candidate in self._INTENT_ORDER:
            if any(kw in lower for kw in self.PATTERNS[candidate]):
                intent = candidate
                break

        # Domain: first matching category wins
        domain = "general"
        for dom, keywords in self.DOMAIN_PATTERNS.items():
            if any(kw in lower for kw in keywords):
                domain = dom
                break

        labels  = self._extract_labels(lower)
        subject = self._extract_subject(lower, intent)

        return {
            "intent":    intent,
            "subject":   subject,
            "labels":    labels,
            "threshold": 0.85,
            "domain":    domain,
        }

    def generate_ledge_program(self, text: str) -> str:
        """
        Generate a valid Ledge program from an English description.

        The program always:
          - Handles uncertainty explicitly
          - Has a safe fallback when confidence is low
          - Includes the input text as the analysis target
        """
        parsed = self.parse_intent(text)
        intent  = parsed["intent"]
        labels  = parsed["labels"]

        escaped    = text.replace("\\", "\\\\").replace('"', '\\"')
        input_line = f'define input as "{escaped}"'

        lines: List[str] = [
            "# Generated by Ledge NL Interface",
            f"# Intent: {intent}",
            input_line,
        ]

        if intent == "triage":
            cats = labels or ["urgent", "routine", "monitor"]
            lines += _classify_block(cats, escalate=True)

        elif intent == "sentiment":
            cats = labels or ["positive", "negative", "neutral"]
            lines += _classify_block(cats, label="Sentiment")

        elif intent == "summarize":
            lines += [
                'define result as analyze(input) using "summarize"',
                "if is_confident(result):",
                '    show "Summary:"',
                "    show value_of(result)",
                "    show confidence_of(result)",
                "else:",
                '    show "Uncertain: needs human review"',
                "    show confidence_of(result)",
            ]

        else:  # classify / analyze
            cats = (labels
                    or (["high", "medium", "low"] if intent == "analyze"
                        else ["yes", "no"]))
            lines += _classify_block(cats)

        return "\n".join(lines)

    def run(self, text: str, input_values: Optional[Dict] = None,
            backend=None) -> Tuple[List[str], str]:
        """
        parse_intent → generate_ledge_program → execute.
        Returns (output_lines, generated_program_source).
        """
        from ledge_lang import run as ledge_run

        program = self.generate_ledge_program(text)
        output: List[str] = []

        try:
            ledge_run(
                program,
                output_fn=lambda x: output.append(x),
                ai_backend=backend,
                reset_audit=True,
            )
        except Exception as exc:
            output.append(f"Error: {exc}")

        return output, program

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _extract_labels(self, lower: str) -> Optional[List[str]]:
        """Extract classification labels from 'as X or Y' or trailing 'X or Y'."""
        # "as X or Y"  (e.g. "classify this as spam or not spam")
        m = re.search(
            r'\bas\s+(.+?)\s+or\s+(.+?)(?:\s*$|\s+for\b|\s+to\b)', lower
        )
        if m:
            return [m.group(1).strip(), m.group(2).strip()]

        # "be/is/whether X or Y"  (e.g. "is this clause risky or safe")
        m = re.search(
            r'(?:be|is|whether)\s+(.+?)\s+or\s+(.+?)(?:\s*$|\s+for\b|\s+to\b)',
            lower,
        )
        if m:
            return [m.group(1).strip(), m.group(2).strip()]

        # trailing "X or Y" — short words only
        m = re.search(
            r'\b(\w+(?:\s+\w+)?)\s+or\s+(\w+(?:\s+\w+)?)\s*$', lower
        )
        if m:
            l1, l2 = m.group(1).strip(), m.group(2).strip()
            _stop = {"the", "a", "an", "this", "that", "it", "is", "be"}
            if l1 not in _stop and l2 not in _stop:
                return [l1, l2]

        return None

    def _extract_subject(self, lower: str, intent: str) -> str:
        """Extract the subject phrase following the intent keyword."""
        for kw in self.PATTERNS.get(intent, []):
            idx = lower.find(kw)
            if idx >= 0:
                after = lower[idx + len(kw):].strip()
                after = re.sub(r'^(this|these|the|a|an)\s+', '', after)
                return after.split(" as ")[0].split(" for ")[0].strip()
        return lower


# ── Program fragment builders ─────────────────────────────────────────────────

def _classify_block(cats: List[str], label: str = "Result",
                    escalate: bool = False) -> List[str]:
    cats_str = ", ".join(f'"{c}"' for c in cats)
    fallback  = ('    show "ESCALATE TO HUMAN: confidence insufficient"'
                 if escalate else
                 '    show "Uncertain: needs human review"')
    return [
        f"define result as classify(input) using [{cats_str}]",
        "if is_confident(result):",
        f'    show "{label}:"',
        "    show value_of(result)",
        "    show confidence_of(result)",
        "else:",
        fallback,
        "    show confidence_of(result)",
    ]
