; Ledge Compiled Output
; Generated by ledge_lang.compiler.codegen
; Target: x86_64-unknown-linux-gnu

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; External declarations
declare i32 @printf(i8* nocapture readonly, ...)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @strcpy(i8*, i8*)
declare i64 @strlen(i8*)
declare i8* @strcat(i8*, i8*)

; Runtime support
@.fmt_double = private constant [4 x i8] c"%g\0A\00"
@.fmt_string = private constant [4 x i8] c"%s\0A\00"
@.fmt_int    = private constant [5 x i8] c"%lld\0A\00"
@.str_true   = private constant [5 x i8] c"true\00"
@.str_false  = private constant [6 x i8] c"false\00"
@.str_nothing = private constant [8 x i8] c"nothing\00"

define double @fn_factorial(double %arg_n) {
  entry:
  %param_n1 = alloca double, align 8
  store double %arg_n, double* %param_n1, align 8
  %t2 = load double, double* %param_n1, align 8
  %t4 = fcmp ole double %t2, 1.0
  %t5 = uitofp i1 %t4 to double
  %t6 = fcmp one double %t5, 0.0
  br i1 %t6, label %then2, label %if_end1
then2:
  ret double 1.0
  br label %if_end1
if_end1:
  %t7 = load double, double* %param_n1, align 8
  %t8 = load double, double* %param_n1, align 8
  %t9 = fsub double %t8, 1.0
  %t10 = call double @fn_factorial(double %t9)
  %t11 = fmul double %t7, %t10
  ret double %t11
  ret double 0.0
}

  %t12 = call double @fn_factorial(double 10.0)
  %t13 = getelementptr [4 x i8], [4 x i8]* @.fmt_double, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* %t13, double %t12)
  ret i32 0
}
